apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-data
spec:
  replicas: 3
  selector:
    matchLabels:
      app: market-data
  template:
    metadata:
      labels:
        app: market-data
    spec:
      containers:
      - name: market-data
        image: ${ECR_REPOSITORY_PREFIX}-market-data:latest
        ports:
        - containerPort: 8083
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: ${DEPLOY_ENV}
        - name: AWS_KMS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-kms-keys
              key: market-data-key
        volumeMounts:
        - name: ssl-cert
          mountPath: "/etc/ssl/certs"
          readOnly: true
      volumes:
      - name: ssl-cert
        secret:
          secretName: trading-platform-certs
