apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-tls
spec:
  secretName: app-tls-secret
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  subject:
    organizations:
      - ABC Trading Platform
  commonName: ${DOMAIN_NAME}
  dnsNames:
    - ${DOMAIN_NAME}
    - "*.${DOMAIN_NAME}"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
