apiVersion: apps/v1
kind: Deployment
metadata:
  name: settlement
spec:
  replicas: 3
  selector:
    matchLabels:
      app: settlement
  template:
    metadata:
      labels:
        app: settlement
    spec:
      containers:
      - name: settlement
        image: ${ECR_REPOSITORY_PREFIX}-settlement:latest
        ports:
        - containerPort: 8095
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: ${DEPLOY_ENV}
        - name: AWS_KMS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-kms-keys
              key: settlement-key
        volumeMounts:
        - name: ssl-cert
          mountPath: "/etc/ssl/certs"
          readOnly: true
      volumes:
      - name: ssl-cert
        secret:
          secretName: trading-platform-certs
