apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-feed
spec:
  replicas: 3
  selector:
    matchLabels:
      app: price-feed
  template:
    metadata:
      labels:
        app: price-feed
    spec:
      containers:
      - name: price-feed
        image: ${ECR_REPOSITORY_PREFIX}-price-feed:latest
        ports:
        - containerPort: 8089
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: ${DEPLOY_ENV}
        - name: AWS_KMS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-kms-keys
              key: price-feed-key
        volumeMounts:
        - name: ssl-cert
          mountPath: "/etc/ssl/certs"
          readOnly: true
      volumes:
      - name: ssl-cert
        secret:
          secretName: trading-platform-certs
