apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliance
spec:
  replicas: 3
  selector:
    matchLabels:
      app: compliance
  template:
    metadata:
      labels:
        app: compliance
    spec:
      containers:
      - name: compliance
        image: ${ECR_REPOSITORY_PREFIX}-compliance:latest
        ports:
        - containerPort: 8094
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: ${DEPLOY_ENV}
        - name: AWS_KMS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-kms-keys
              key: compliance-key
        volumeMounts:
        - name: ssl-cert
          mountPath: "/etc/ssl/certs"
          readOnly: true
      volumes:
      - name: ssl-cert
        secret:
          secretName: trading-platform-certs
