apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base/frontend
  - ../../base/backend-services
  - ../../base/axon-server
  - ../../base/database

namespace: prod

commonLabels:
  environment: prod
