apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification
        image: ${ECR_REPOSITORY_PREFIX}-notification:latest
        ports:
        - containerPort: 8091
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: ${DEPLOY_ENV}
        - name: AWS_KMS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-kms-keys
              key: notification-key
        volumeMounts:
        - name: ssl-cert
          mountPath: "/etc/ssl/certs"
          readOnly: true
      volumes:
      - name: ssl-cert
        secret:
          secretName: trading-platform-certs
