apiVersion: v1
kind: Service
metadata:
  name: axon-server
spec:
  type: ClusterIP
  ports:
  - name: gui
    port: 8024
    targetPort: 8024
  - name: grpc
    port: 8124
    targetPort: 8124
  selector:
    app: axon-server
